### ISSUE TITLE
Handle files/folders which get deleted

### ISSUE THREAD

**Issue by nelsonic** [ideaq/faster#2]
Currently we are seeing the following error:

``` sh
fs.js:1062
    throw errnoException(process._errno, 'watch');
          ^
Error: watch ENOENT
    at errnoException (fs.js:1030:11)
    at FSWatcher.start (fs.js:1062:11)
    at Object.fs.watch (fs.js:1087:11)
    at /Users/n/code/faster/index.js:70:12
    at Array.map (native)
    at /Users/n/code/faster/index.js:68:18
    at /Users/n/code/faster/index.js:24:14
    at Object.oncomplete (fs.js:107:15)
```

**Comment by nelsonic** [comment]
Think we have a solution for this, but need to write some tests to confirm it.

**Comment by nelsonic** [comment]
Tests... :wink: 
see: https://github.com/ideaq/faster/issues/14
