### ISSUE TITLE
no such file or directory, open 'socket.io-client/dist/socket.io.js'

### ISSUE THREAD

**Issue by nelsonic** [ideaq/faster#56]
![image](https://user-images.githubusercontent.com/194400/41196986-941ca896-6c46-11e8-8623-330463f0861e.png)

```sh
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/code/time-mvp/node_modules/faster/socket.io-client/dist/socket.io.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Server.<anonymous> (/code/time-mvp/node_modules/faster/lib/webserver.js:25:17)
    at Server.<anonymous> (/code/time-mvp/node_modules/engine.io/lib/server.js:471:22)
    at Server.<anonymous> (/code/time-mvp/node_modules/socket.io/lib/index.js:343:16)
    at emitTwo (events.js:126:13)
    at Server.emit (events.js:214:7)
    at parserOnIncoming (_http_server.js:619:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:112:17)
npm ERR! code ELIFECYCLE
```

**Comment by nelsonic** [comment]
https://github.com/dwyl/faster/blob/a81add2bc17c331f48ca8c1d3255f89e34e3204c/lib/webserver.js#L23
we need to check if the "_parent_" directory is `node_modules` ...
